[package]
name = "libdiffuzz"
version = "0.1.0"
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "0.2.43"
rand = "0.5.5"

[profile.release]
panic = "abort"
